AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Style/Documentation:
  Enabled: false
